version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: C:\gopath

clone_folder: c:\gopath\src\goa.design\goa

install:
  - go version
  - set PATH=c:\msys64\usr\bin;%GOPATH%\bin;%PATH%

build_script:
  - pwd
  - ls
  - if "%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%" == "" ( make travis GOA_BRANCH="%APPVEYOR_REPO_BRANCH%" ) else ( make travis GOA_BRANCH="%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%" )

test: off

deploy: off
